version: '3.8'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
    network_mode: "bridge"
